spring:
  application:
    name: hello
  thymeleaf:
    cache: false

---
spring:
  profiles: prod

---
spring:
  profiles: dev

hello:
  message: "hello (dev)"

---
spring:
  profiles: test

hello:
  message: "hello (test)"

---
spring:
  profiles: local

hello:
  message: "hello (local)"

logging.level:
  hello: DEBUG